---
title: "Cleaning Gapminder Data"
author: "Tyler Byers"
date: "February 28, 2015"
output: html_document
---

This is my script for cleaning the Gapminder Data for the Data Vis project.  The data sets I'll combine are the GDP, Sugar Consumption, BMI, and Calories data sets

```{r load data}
library(ggplot2)
library(reshape2)
library(dplyr)
library(xlsx)
sugar <- read.xlsx('indicator sugar_consumption.xlsx',1)
bmi <- read.xlsx('Indicator_BMI male ASM.xlsx', 1)
gdp <- read.xlsx('GDPpercapitaconstant2000US.xlsx', 1)
cals <- read.xlsx('indicator food_consumption.xlsx', 1)
regions <- read.xlsx('Color- Regions.xlsx', 2)
```

###Clean Sugar Data

```{r, clean sugar}
sugar$X2004 <- NULL # 2004 data was a copy of 2003 data
colnames(sugar) <- substr(names(sugar), 2, 5)  # Remove the X from the Year
sugar$A..1 <- NULL # strange last column
sugar.t <- data.frame(t(sugar)) # Create a transposed data frame to be used later
names(sugar)[1] <- 'Country' # Rename column 1 into "country"
sugar.long <- melt(sugar, id.var = 'Country') # Melt into 3-variable dataframe
names(sugar.long)[2] <- 'year' # Rename from "variable"
names(sugar.long)[3] <- 'gmssugar' # Rename from "value"
```

###Clean BMI Data

```{r clean bmi}
colnames(bmi) <- substr(names(bmi), 2, 5)
names(bmi)[1] <- 'Country'
bmi.long <- melt(bmi, id.var = 'Country')
names(bmi.long)[2] <- 'year'
names(bmi.long)[3] <- 'bmi'
```

###Clean GDP data

```{r clean gdp}
names(gdp) <- substr(names(gdp), 2, 5)
names(gdp)[1] <- 'Country'
gdp.long <- melt(gdp, id.var = 'Country')
names(gdp.long)[2] <- 'year'
names(gdp.long)[3] <- 'gdp'
```

### Clean Calorie data

```{r clean calories}
names(cals) <- substr(names(cals), 2, 5)
names(cals)[1] <- 'Country'
cals.long <- melt(cals, id.var = 'Country')
names(cals.long)[2] <- 'year'
names(cals.long)[3] <- 'calories'
```

### Clean Regions

```{r clean regions}
regions <- regions[,1:3]
names(regions) <- c('Country','Region','Digraph')
```

###Merge Data

```{r merge data}
sugar.bmi <- merge(sugar.long, bmi.long)
sugar.bmi.gdp <- merge(sugar.bmi, gdp.long)
cals.sugar.bmi.gdp <- merge(sugar.bmi.gdp, cals.long)
df_final <- merge(cals.sugar.bmi.gdp, regions)
```

```{r gms_sugar plot}
ggplot(aes(x = gmssugar, y = bmi), data = sugar.bmi.gdp) +
  geom_jitter(alpha = 0.5, color = 'orange') + 
  geom_smooth(method = 'lm', color = 'black') +
  xlab('Daily Sugar (gm/person)') + ylab('Avg Male BMI')  +
  ggtitle('Male BMI vs Sugar Consumption') +
  theme_minimal()
```

###Write Data

```{r write data}
# Write all data, with NAs
write.csv(df_final, file = 'cals_sugar_bmi_gdp.csv', row.names = FALSE)
# Write only data with complete cases
write.csv(df_final[complete.cases(df_final),], 
          file = 'compcases_cals_sugar_bmi_gdp.csv', row.names = FALSE)
```

